<div class="row">
    <div class="col-12 pb-5">
        <div class="btn-group dropup">
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-globe"></i>
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="<?php $gs->getPathFor($gs->getRouteName(), 'de_de'); ?>">Deutsch</a>
                <a class="dropdown-item" href="<?php $gs->getPathFor($gs->getRouteName(), 'en_us'); ?>">English</a>
            </div>
        </div>
    </div>
</div>
