<div class="row">
    <div class="col-12 py-5 text-center">
        <h1>
            Gulp Skeleton - InsanityMeetsHH
            <a href="https://github.com/InsanityMeetsHH/gulp-templating" target="_blank"><i class="fab fa-inverse fa-github" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="GitHub"></i></a>
        </h1>
    </div>
</div>
<div class="row text-center justify-content-center">
    <div class="col-12">
        <span style="font-size: 1.75rem;"><?php echo $lang['included']; ?></span>
        <h1 id="counter"></h1>
        <img id="boo" src="img/slick/ajax-loader.gif" data-src="https://via.placeholder.com/266x140/2E97BF/0f0f0f?text=LazyLoad%20Image" alt="image" class="img-fluid" />
        <img id="confetti" src="img/slick/ajax-loader.gif" data-src="https://via.placeholder.com/266x140/0c0c0c/212121?text=LazyLoad%20Image" alt="image" class="img-fluid" />
    </div>
    <div class="col-12 col-md-8 pb-5">
        <div class="slider slider-brands" data-slick='{"responsive": [{"breakpoint": 575,"settings": {"slidesToShow": 2, "slidesToScroll": 1}},{"breakpoint": 991, "settings": {"slidesToShow": 3, "slidesToScroll": 1}}]}'>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-3x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fas fa-stack-1x fa-inverse fa-bold"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-10x">
                    <span class="fa-layers">
                        <i class="far fa-square"></i>
                        <i class="fas fa-bold fa-inverse" data-fa-transform="shrink-6"></i>
                    </span>
                </div>
                <a href="https://getbootstrap.com/" target="_blank" class="d-block label"><?php echo $lang['bootstrap']; ?></a>
            </div>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-3x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fab fa-stack-1x fa-inverse fa-font-awesome-flag"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-10x">
                    <span class="fa-layers">
                        <i class="far fa-square"></i>
                        <i class="fab fa-font-awesome-flag fa-inverse" data-fa-transform="shrink-6"></i>
                    </span>
                </div>
                <a href="https://fontawesome.com/" target="_blank" class="d-block label"><?php echo $lang['fontawesome']; ?></a>
            </div>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-3x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fas fa-stack-1x fa-inverse fa-images"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-10x">
                    <span class="fa-layers">
                        <i class="fas fa-square"></i>
                        <i class="fas fa-image fa-inverse" data-fa-transform="shrink-7"></i>
                        <i class="fas fa-chevron-left fa-inverse" data-fa-transform="shrink-13 left-6"></i>
                        <i class="fas fa-chevron-right fa-inverse" data-fa-transform="shrink-13 right-6"></i>
                    </span>
                </div>
                <a href="http://kenwheeler.github.io/slick/" target="_blank" class="d-block label"><?php echo $lang['slick']; ?></a>
            </div>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-3x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fas fa-stack-1x fa-inverse fa-image"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-10x">
                    <span class="fa-layers">
                        <i class="fas fa-square"></i>
                        <i class="fas fa-image fa-inverse" data-fa-transform="shrink-4"></i>
                        <i class="fas fa-sync" data-fa-transform="shrink-14 up-2.5 right-4"></i>
                    </span>
                </div>
                <a href="https://www.andreaverlicchi.eu/lazyload/" target="_blank" class="d-block label"><?php echo $lang['lazyload']; ?></a>
            </div>
            <div class="slider-item">
                <!-- Fonts with CSS Example (use only without Fontawesome JavaScript) -->
                <!--<span class="fa-stack fa-3x">
                    <i class="far fa-stack-2x fa-square"></i>
                    <i class="fab fa-stack-1x fa-inverse fa-css3"></i>
                </span><br/>-->

                <!-- SVG with JavaScript Example -->
                <div class="fa-10x">
                    <span class="fa-layers">
                        <i class="fas fa-square"></i>
                        <i class="fas fa-user-secret fa-inverse" data-fa-transform="shrink-4"></i>
                        <i class="fab fa-css3" data-fa-transform="shrink-14 down-4 right-3.5"></i>
                        <i class="fab fa-html5" data-fa-transform="shrink-14 down-4 left-3.5"></i>
                    </span>
                </div>
                <a href="https://www.npmjs.com/package/cssuseragent" target="_blank" class="d-block label"><?php echo $lang['cssua']; ?></a>
            </div>
            <div class="slider-item">
                <!-- SVG with JavaScript Example -->
                <div class="fa-10x">
                    <span class="fa-layers">
                        <i class="fas fa-circle"></i>
                        <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-15 up-4 left-4"></i>
                        <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-15 down-0 left-5.5"></i>
                        <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-15 down-4.2 right-4"></i>
                        <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-13 down-4 left-2"></i>
                        <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-13"></i>
                        <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-14 right-5"></i>
                        <i class="fas fa-circle fa-inverse" data-fa-transform="shrink-14 up-5"></i>
                    </span>
                </div>
                <a href="https://github.com/insites/cookieconsent" target="_blank" class="d-block label"><?php echo $lang['cookieconsent']; ?></a>
            </div>
        </div>
    </div>
    <div class="col-12 pb-5">
        <div class="row">
            <div class="col-12 col-md-6 pb-5 pb-md-0">
                <h3 class="pb-2"><?php echo $lang['lazyload-example']; ?></h3>
                <img src="img/slick/ajax-loader.gif" data-src="https://via.placeholder.com/266x140/2E97BF/212121?text=LazyLoad%20Image" alt="image" class="img-fluid"/>
            </div>
            <div class="col-12 col-md-6">
                <h3 class="pb-2"><?php echo $lang['cssua-monitor']; ?></h3>
                <div class="cssua-monitor"></div>
            </div>
        </div>
    </div>
</div>
